In [2]:
import random 
import numpy as np
import pandas as pd
import re

In [1]:
# Code untuk generate randomly data-data random

def generate_username():
    #polanya 9 digit alphabetic + _ + 3 numeric
    list_vocal = ["a","i","u","e","o"]
    list_consonant = list(set(map(chr, range(ord('a'), ord('z')+1))).difference(set(list_vocal)))
    list_number = [str(x) for x in range(10)]
    
    acak_pertama = [random.choice(list_consonant) if random.randint(1,3) == 1 else random.choice(list_vocal) for x in range(9)]
    acak_kedua = [random.choice(list_number) for x in range(3)]
    
    return("".join(acak_pertama)+"_"+"".join(acak_kedua))


def generate_email():
    #polanya 15 digit alphabetic + _ + 3 numeric + @ + gmail/hotmail/yahoo.com
    list_vocal = ["a","i","u","e","o"]
    list_consonant = list(set(map(chr, range(ord('a'), ord('z')+1))).difference(set(list_vocal)))
    list_number = [str(x) for x in range(10)]
    list_email = ["gmail.com","hotmail.com","yahoo.com","outlook.com"]
    
    acak_pertama = [random.choice(list_vocal) if random.randint(1,3) == 1 else random.choice(list_consonant) for x in range(15)]
    acak_kedua = [random.choice(list_number) for x in range(3)]
    acak_ketiga = random.choice(list_email)
    
    return("".join(acak_pertama)+"_"+"".join(acak_kedua) + "@" + acak_ketiga)

def generate_phone():
    #08 56/98/12/... + 8 digit random
    list_provider = ["12","18","19","59","77","78",'38','31','32','33','95','96','97','98','99','56','57','58','55','12','22','13']
    list_number = [str(x) for x in range(10)]
    
    acak_8_digit = [random.choice(list_number) for x in range(8)]
    
    return("08"+random.choice(list_provider)+"".join(acak_8_digit))

kota_jabar = """Kabupaten Bandung
                Kabupaten Bandung Barat
                Kabupaten Bekasi
                Kabupaten Bogor
                Kabupaten Ciamis
                Kabupaten Cianjur
                Kabupaten Cirebon
                Kabupaten Garut
                Kabupaten Indramayu
                Kabupaten Karawang
                Kabupaten Kuningan
                Kabupaten Majalengka
                Kabupaten Pangandaran
                Kabupaten Purwakarta
                Kabupaten Subang
                Kabupaten Sukabumi
                Kabupaten Sumedang
                Kabupaten Tasikmalaya
                Kota Bandung
                Kota Banjar
                Kota Bekasi
                Kota Bogor
                Kota Cimahi
                Kota Cirebon
                Kota Depok
                Kota Sukabumi
                Kota Tasikmalaya""".split("\n")

# Generate Artificial Data

| kolom | keterangan |
| -- | -- |
| buyer_id | ID buyer/ user_id buyer |
| email | Email (ceritanya) milik user_id |
| phone | Phone (ceritanya) milik user_id |
| city | Kota/Kabupaten Asal milik user_id (ceritanya juga pelanggan dari Jawa Barat) |
| trx | Total transaksi dalam 30 hari terakhir |
| ltv | Total GMV/Amount Transactions dalam 30 hari terakhir, satuan dalam rupiah |
| total_visit | Total aktifitas membuka aplikasi selama 30 hari terakhir |

*Disclaimer: Jika pas pengacakan ada data yang mirip dengan data pribadi, mohon diacak kembali ya*

In [3]:
# Set Seed
np.random.seed(29102020) #29-10-2020

# Mau ada berapa user?
n = 100

# Do not touch
data_homework = pd.DataFrame({"buyer_id":list(range(1,n+1,1)),
                          "username": [generate_username() for x in range(n)],
                          "email" : [generate_email() for x in range(n)],
                          "phone": [generate_phone() for x in range(n)],
                          "city": [random.choice(kota_jabar) for x in range(n)],
                          "trx": [random.randint(1,100) for x in range(n)],
                          "ltv": [random.randint(1000,10000000) for x in range(n)],
                          "total_visit": [random.randint(1,100) for x in range(n)]
                         })
data_homework

    buyer_id       username  ...      ltv total_visit
0          1  neaayjaai_172  ...  3806192          24
1          2  ewwuiaubm_343  ...  8869323          72
2          3  foaeakeme_076  ...  1274377          41
3          4  ueaieueua_937  ...  5734740          25
4          5  yaqaoihlg_573  ...  5717164          14
..       ...            ...  ...      ...         ...
95        96  ueeneeeng_101  ...  7181502          14
96        97  qiilnovei_242  ...  9433665          12
97        98  ouifpioot_746  ...  9116975          88
98        99  uaaoaicgi_716  ...  1271836          37
99       100  uwaaiieaa_686  ...  1369785          70

[100 rows x 8 columns]

# Soal 1

In [4]:
data_homework["kategori_visit"] =data_homework["total_visit"].map(lambda x: "pendatang_baru" if 0<=x<=10 else 
                                                                  "pendatang_normal" if 11<=x<=30 
                                                                  else "pendatang_lama")
data_homework

    buyer_id       username  ... total_visit    kategori_visit
0          1  neaayjaai_172  ...          24  pendatang_normal
1          2  ewwuiaubm_343  ...          72    pendatang_lama
2          3  foaeakeme_076  ...          41    pendatang_lama
3          4  ueaieueua_937  ...          25  pendatang_normal
4          5  yaqaoihlg_573  ...          14  pendatang_normal
..       ...            ...  ...         ...               ...
95        96  ueeneeeng_101  ...          14  pendatang_normal
96        97  qiilnovei_242  ...          12  pendatang_normal
97        98  ouifpioot_746  ...          88    pendatang_lama
98        99  uaaoaicgi_716  ...          37    pendatang_lama
99       100  uwaaiieaa_686  ...          70    pendatang_lama

[100 rows x 9 columns]

# Soal 2

In [5]:
data_homework.loc[:,"kategori_pelanggan"] = np.where(data_homework['trx']>=20, 
                                    (np.where((data_homework['ltv']>=2500000) &
                                              (data_homework['ltv']<2500000), "very_loyal", "loyal")),
                                    "normal")
data_homework.head()

   buyer_id       username  ...    kategori_visit kategori_pelanggan
0         1  neaayjaai_172  ...  pendatang_normal              loyal
1         2  ewwuiaubm_343  ...    pendatang_lama              loyal
2         3  foaeakeme_076  ...    pendatang_lama              loyal
3         4  ueaieueua_937  ...  pendatang_normal              loyal
4         5  yaqaoihlg_573  ...  pendatang_normal              loyal

[5 rows x 10 columns]

# Soal 3

In [ ]:
data_homework['domain']=data_homework['email'].apply(lambda x: x.split('@')[1])
data_homework

,buyer_id,username,email,phone,city,trx,ltv,total_visit,kategori_visit,kategori_pelanggan,domain
0,1,quiuumioo_819,wuznepblrfnbxaz_855@gmail.com,085859904012,Kota Tasikmalaya,67,467731,20,pendatang_normal,loyal,gmail.com
1,2,oiiajaeui_522,kledwujiidsnnav_708@gmail.com,089739127183,Kabupaten Sumedang,43,5643699,25,pendatang_normal,loyal,gmail.com
2,3,auiuiweza_587,qwouizomrbunuzf_278@yahoo.com,083135904660,Kota Depok,33,3583128,22,pendatang_normal,loyal,yahoo.com
3,4,uaucaaaej_648,oiabccriyedglfp_704@hotmail.com,081354621886,Kabupaten Bogor,73,1464681,71,pendatang_lama,loyal,hotmail.com
4,5,luagtdouh_042,zauwqrnbaubkjjm_258@hotmail.com,089908513528,Kota Bekasi,96,562206,58,pendatang_lama,loyal,hotmail.com
...,...,...,...,...,...,...,...,...,...,...,...
95,96,ukjeoooee_885,guguphuzwdogytb_408@hotmail.com,083144599105,Kabupaten Cirebon,75,3053116,14,pendatang_normal,loyal,hotmail.com
96,97,reefeezeu_891,iydrbperqmfgcfo_062@outlook.com,081856710182,Kota Banjar,80,1928013,81,pendatang_lama,loyal,outlook.com
97,98,gouabieoj_236,aauxdxohhhiiegi_253@outlook.com,089780339417,Kabupaten Purwakarta,66,3817684,37,pendatang_lama,loyal,outlook.com
98,99,aiixpigea_770,teuatmbawtqbpaf_054@yahoo.com,085642282639,Kabupaten Bandung Barat,55,1259369,45,pendatang_lama,loyal,yahoo.com
99,100,auyooecai_436,omxrevjogqbusjj_841@hotmail.com,089959773094,Kabupaten Sumedang,48,1913864,89,pendatang_lama,loyal,hotmail.com

In [ ]:
a = data_homework.groupby(['domain']).mean().reset_index()[['domain','trx']]
a

        domain        trx
0    gmail.com  51.588235
1  hotmail.com  53.161290
2  outlook.com  43.666667
3    yahoo.com  47.357143

In [ ]:
conditions = [
    (data_homework['domain'] == 'gmail.com') & (data_homework['trx']>a['trx'][0]),
    (data_homework['domain'] == 'hotmail.com') & (data_homework['trx']>a['trx'][1]),
    (data_homework['domain'] == 'outlook.com') & (data_homework['trx']>a['trx'][2]),
    (data_homework['domain'] == 'yahoo.com') & (data_homework['trx']>a['trx'][3])]
choices = ['True', 'True', 'True', 'True']
data_homework['best_email_customer'] = np.select(conditions, choices, default='False')
data_homework

,buyer_id,username,email,phone,city,trx,ltv,total_visit,kategori_visit,kategori_pelanggan,domain,best_email_customer
0,1,quiuumioo_819,wuznepblrfnbxaz_855@gmail.com,085859904012,Kota Tasikmalaya,67,467731,20,pendatang_normal,loyal,gmail.com,True
1,2,oiiajaeui_522,kledwujiidsnnav_708@gmail.com,089739127183,Kabupaten Sumedang,43,5643699,25,pendatang_normal,loyal,gmail.com,False
2,3,auiuiweza_587,qwouizomrbunuzf_278@yahoo.com,083135904660,Kota Depok,33,3583128,22,pendatang_normal,loyal,yahoo.com,False
3,4,uaucaaaej_648,oiabccriyedglfp_704@hotmail.com,081354621886,Kabupaten Bogor,73,1464681,71,pendatang_lama,loyal,hotmail.com,True
4,5,luagtdouh_042,zauwqrnbaubkjjm_258@hotmail.com,089908513528,Kota Bekasi,96,562206,58,pendatang_lama,loyal,hotmail.com,True
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,ukjeoooee_885,guguphuzwdogytb_408@hotmail.com,083144599105,Kabupaten Cirebon,75,3053116,14,pendatang_normal,loyal,hotmail.com,True
96,97,reefeezeu_891,iydrbperqmfgcfo_062@outlook.com,081856710182,Kota Banjar,80,1928013,81,pendatang_lama,loyal,outlook.com,True
97,98,gouabieoj_236,aauxdxohhhiiegi_253@outlook.com,089780339417,Kabupaten Purwakarta,66,3817684,37,pendatang_lama,loyal,outlook.com,True
98,99,aiixpigea_770,teuatmbawtqbpaf_054@yahoo.com,085642282639,Kabupaten Bandung Barat,55,1259369,45,pendatang_lama,loyal,yahoo.com,True
99,100,auyooecai_436,omxrevjogqbusjj_841@hotmail.com,089959773094,Kabupaten Sumedang,48,1913864,89,pendatang_lama,loyal,hotmail.com,False

# Soal 4

In [ ]:
def is_prime(x):
    if x < 4:
        return True
    if all([(x > 2), (x % 2 == 0)]):
        return False
    else:
        return np.array([*map(lambda y: ((x % y) == 0).sum(), np.arange(1, x + 1))]).sum() == 2

In [ ]:
data_homework['voucher_discount']=data_homework["trx"].map(lambda x: 'layak' if is_prime(x)==True else 'tidak layak')
data_homework

,buyer_id,username,email,phone,city,trx,ltv,total_visit,kategori_visit,kategori_pelanggan,domain,best_email_customer,voucher_discount
0,1,quiuumioo_819,wuznepblrfnbxaz_855@gmail.com,085859904012,Kota Tasikmalaya,67,467731,20,pendatang_normal,loyal,gmail.com,True,layak
1,2,oiiajaeui_522,kledwujiidsnnav_708@gmail.com,089739127183,Kabupaten Sumedang,43,5643699,25,pendatang_normal,loyal,gmail.com,False,layak
2,3,auiuiweza_587,qwouizomrbunuzf_278@yahoo.com,083135904660,Kota Depok,33,3583128,22,pendatang_normal,loyal,yahoo.com,False,tidak layak
3,4,uaucaaaej_648,oiabccriyedglfp_704@hotmail.com,081354621886,Kabupaten Bogor,73,1464681,71,pendatang_lama,loyal,hotmail.com,True,layak
4,5,luagtdouh_042,zauwqrnbaubkjjm_258@hotmail.com,089908513528,Kota Bekasi,96,562206,58,pendatang_lama,loyal,hotmail.com,True,tidak layak
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,ukjeoooee_885,guguphuzwdogytb_408@hotmail.com,083144599105,Kabupaten Cirebon,75,3053116,14,pendatang_normal,loyal,hotmail.com,True,tidak layak
96,97,reefeezeu_891,iydrbperqmfgcfo_062@outlook.com,081856710182,Kota Banjar,80,1928013,81,pendatang_lama,loyal,outlook.com,True,tidak layak
97,98,gouabieoj_236,aauxdxohhhiiegi_253@outlook.com,089780339417,Kabupaten Purwakarta,66,3817684,37,pendatang_lama,loyal,outlook.com,True,tidak layak
98,99,aiixpigea_770,teuatmbawtqbpaf_054@yahoo.com,085642282639,Kabupaten Bandung Barat,55,1259369,45,pendatang_lama,loyal,yahoo.com,True,tidak layak
99,100,auyooecai_436,omxrevjogqbusjj_841@hotmail.com,089959773094,Kabupaten Sumedang,48,1913864,89,pendatang_lama,loyal,hotmail.com,False,tidak layak

# Soal 5

In [ ]:
#========================================================== n = 3 ==========================================================#
string = ""

x = 3
bar = x
# Looping Baris
while bar >= 0:
    # Looping Kolom Spasi Kosong
    kol = bar
    while kol > 0:
        string = string + "   "
        kol = kol - 1
    # Looping Kolom Bintang Sisi Kiri
    kiri = 1
    while kiri < (x - (bar-1)):
        string = string + " * "
        kiri = kiri + 1
    # Looping Kolom Bintang Sisi Kanan
    kanan = 1
    while kanan < kiri -1:
        string = string + " * "
        kanan = kanan + 1

    string = string + "\n\n"
    bar = bar - 1

bar = 1	
# Looping Baris
while bar <= x:
    kol = bar+1
    # Looping Kolom Spasi Kosong
    while kol > 1:
        string = string + "   "
        kol = kol - 1
    # Looping Kolom Bintang Sisi Kiri
    kiri = 0
    while kiri < (x - bar):
        string = string + " * "
        kiri = kiri + 1
    # Looping Kolom Bintang Sisi Kanan
    kanan = kiri
    while kanan > 1:
        string = string + " * "
        kanan = kanan - 1

    string = string + "\n\n"
    bar = bar + 1
print (string)

#========================================================== n = 5 ==========================================================#
string = ""

x = 5
bar = x
# Looping Baris
while bar >= 0:
    # Looping Kolom Spasi Kosong
    kol = bar
    while kol > 0:
        string = string + "   "
        kol = kol - 1
    # Looping Kolom Bintang Sisi Kiri
    kiri = 1
    while kiri < (x - (bar-1)):
        string = string + " * "
        kiri = kiri + 1
    # Looping Kolom Bintang Sisi Kanan
    kanan = 1
    while kanan < kiri -1:
        string = string + " * "
        kanan = kanan + 1

    string = string + "\n\n"
    bar = bar - 1

bar = 1	
# Looping Baris
while bar <= x:
    kol = bar+1
    # Looping Kolom Spasi Kosong
    while kol > 1:
        string = string + "   "
        kol = kol - 1
    # Looping Kolom Bintang Sisi Kiri
    kiri = 0
    while kiri < (x - bar):
        string = string + " * "
        kiri = kiri + 1
    # Looping Kolom Bintang Sisi Kanan
    kanan = kiri
    while kanan > 1:
        string = string + " * "
        kanan = kanan - 1

    string = string + "\n\n"
    bar = bar + 1
print (string)


#====================================================== n = 10 ===========================================================#
string = ""

x = 10
bar = x
# Looping Baris
while bar >= 0:
    # Looping Kolom Spasi Kosong
    kol = bar
    while kol > 0:
        string = string + "   "
        kol = kol - 1
    # Looping Kolom Bintang Sisi Kiri
    kiri = 1
    while kiri < (x - (bar-1)):
        string = string + " * "
        kiri = kiri + 1
    # Looping Kolom Bintang Sisi Kanan
    kanan = 1
    while kanan < kiri -1:
        string = string + " * "
        kanan = kanan + 1

    string = string + "\n\n"
    bar = bar - 1

bar = 1	
# Looping Baris
while bar <= x:
    kol = bar+1
    # Looping Kolom Spasi Kosong
    while kol > 1:
        string = string + "   "
        kol = kol - 1
    # Looping Kolom Bintang Sisi Kiri
    kiri = 0
    while kiri < (x - bar):
        string = string + " * "
        kiri = kiri + 1
    # Looping Kolom Bintang Sisi Kanan
    kanan = kiri
    while kanan > 1:
        string = string + " * "
        kanan = kanan - 1

    string = string + "\n\n"
    bar = bar + 1
print (string)

       *

    *  *  *

 *  *  *  *  *

    *  *  *

       *






             *

          *  *  *

       *  *  *  *  *

    *  *  *  *  *  *  *

 *  *  *  *  *  *  *  *  *

    *  *  *  *  *  *  *

       *  *  *  *  *

          *  *  *

             *






                            *

                         *  *  *

                      *  *  *  *  *

                   *  *  *  *  *  *  *

                *  *  *  *  *  *  *  *  *

             *  *  *  *  *  *  *  *  *  *  *

          *  *  *  *  *  *  *  *  *  *  *  *  *

       *  *  *  *  *  *  *  *  *  *  *  *  *  *  *

    *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *

 *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *

    *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *

       *  *  *  *  *  *  *  *  *  *  *  *  *  *  *

          *  *  *  *  *  *  *  *  *  *  *  *  *

             *  *  *  *  *  *  *  *  *  *  *

                *  *  *  *  *  *  *  *  *

                   *  *  *  *  *  *  *

                      *  *  *  *  *

                         *  *  *

                            *